### ISSUE TITLE
Make && Make run gives an error

### ISSUE THREAD

**Issue by discochat** [xen/flask-project-template#6]
The error is : 

```
sqlalchemy.exc.InvalidRequestError: Class <class 'social.apps.flask_app.default.models.init_social.<locals>.UserSocialAuth'> does not have a __table__ or __tablename__ specified and does not inherit from an existing table-mapped class.
```

**Comment by discochat** [comment]
After a bit of research the problem lies within the default model for flask in the file the error points to.
Editing this file to add the correct default tablenames fixes the issue.

I guess I'll bring this issue to them.

**Comment by xen** [comment]
Hello, can you please provide full traceback and with command used

**Comment by discochat** [comment]
The make part runs ok. The make run though : 
`[discocat@bbq-cat flask-project-template]$ make run
. venv/bin/activate; python manage.py runserver -h 0.0.0.0 -d -r
/home/discocat/Project/flask-project-template/project/extensions.py:26: FlaskWTFDeprecationWarning: "flask_wtf.CsrfProtect" has been renamed to "CSRFProtect" and will be removed in 1.0.
  csrf = CsrfProtect()
/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/social/apps/flask_app/routes.py:2: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
  from flask.ext.login import login_required, login_user
/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "manage.py", line 75, in <module>
    manager.run()
  File "/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/flask_script/__init__.py", line 156, in __call__
    app = app(**kwargs)
  File "/home/discocat/Project/flask-project-template/project/app.py", line 46, in create_app
    extensions_fabrics(app)
  File "/home/discocat/Project/flask-project-template/project/app.py", line 80, in extensions_fabrics
    init_social(app, db)
  File "/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/social/apps/flask_app/default/models.py", line 30, in init_social
    class UserSocialAuth(_AppSession, db.Model, SQLAlchemyUserMixin):
  File "/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 602, in __init__
    DeclarativeMeta.__init__(self, name, bases, d)
  File "/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/sqlalchemy/ext/declarative/api.py", line 64, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 133, in __init__
    self._setup_inheritance()
  File "/home/discocat/Project/flask-project-template/venv/lib/python3.6/site-packages/sqlalchemy/ext/declarative/base.py", line 430, in _setup_inheritance
    "table-mapped class." % cls
sqlalchemy.exc.InvalidRequestError: Class <class 'social.apps.flask_app.default.models.init_social.<locals>.UserSocialAuth'> does not have a __table__ or __tablename__ specified and does not inherit from an existing table-mapped class.
make: *** [Makefile:7: run] Error 1
`

**Comment by chong** [comment]
I got the same issues.

**Comment by anmir** [comment]
I've got the same issue. How to solve it?
